version: '3'

services:

  mongo:
    container_name: mongodb-container
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - my-datavolume:/data/db


  task-service:
    container_name: tasks-service
    restart: always
    build: .
    working_dir: /CRUD_NODE_MONGO
    volumes:
      - .:/CRUD_NODE_MONGO
    ports:
      - '3000:3000'
    expose: 
      - '3000'
    links:
      - mongo
    depends_on:
      - mongo


volumes:
  my-datavolume:
